In [1]:
import pandas as pd
import numpy as np
sleep_eff=pd.read_csv("Sleep_Efficiency.csv")
sleep_eff.head()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,1,65,Female,2021-03-06 01:00:00,2021-03-06 07:00:00,6.0,0.88,18,70,12,0.0,0.0,0.0,Yes,3.0
1,2,69,Male,2021-12-05 02:00:00,2021-12-05 09:00:00,7.0,0.66,19,28,53,3.0,0.0,3.0,Yes,3.0
2,3,40,Female,2021-05-25 21:30:00,2021-05-25 05:30:00,8.0,0.89,20,70,10,1.0,0.0,0.0,No,3.0
3,4,40,Female,2021-11-03 02:30:00,2021-11-03 08:30:00,6.0,0.51,23,25,52,3.0,50.0,5.0,Yes,1.0
4,5,57,Male,2021-03-13 01:00:00,2021-03-13 09:00:00,8.0,0.76,27,55,18,3.0,0.0,3.0,No,3.0

In [2]:
sleep_eff.tail()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
447,448,27,Female,2021-11-13 22:00:00,2021-11-13 05:30:00,7.5,0.91,22,57,21,0.0,0.0,0.0,No,5.0
448,449,52,Male,2021-03-31 21:00:00,2021-03-31 03:00:00,6.0,0.74,28,57,15,4.0,25.0,0.0,No,3.0
449,450,40,Female,2021-09-07 23:00:00,2021-09-07 07:30:00,8.5,0.55,20,32,48,1.0,NaN,3.0,Yes,0.0
450,451,45,Male,2021-07-29 21:00:00,2021-07-29 04:00:00,7.0,0.76,18,72,10,3.0,0.0,0.0,No,3.0
451,452,18,Male,2021-03-17 02:30:00,2021-03-17 10:00:00,7.5,0.63,22,23,55,1.0,50.0,0.0,No,1.0

In [3]:
sleep_eff.describe()

,ID,Age,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Exercise frequency
count,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,452.000000,432.000000,427.000000,438.000000,446.000000
mean,226.500000,40.285398,7.465708,0.788916,22.615044,52.823009,24.561947,1.641204,23.653396,1.173516,1.791480
std,130.625419,13.172250,0.866625,0.135237,3.525963,15.654235,15.313665,1.356762,30.202785,1.621377,1.428134
min,1.000000,9.000000,5.000000,0.500000,15.000000,18.000000,7.000000,0.000000,0.000000,0.000000,0.000000
25%,113.750000,29.000000,7.000000,0.697500,20.000000,48.250000,15.000000,1.000000,0.000000,0.000000,0.000000
50%,226.500000,40.000000,7.500000,0.820000,22.000000,58.000000,18.000000,1.000000,25.000000,0.000000,2.000000
75%,339.250000,52.000000,8.000000,0.900000,25.000000,63.000000,32.500000,3.000000,50.000000,2.000000,3.000000
max,452.000000,69.000000,10.000000,0.990000,30.000000,75.000000,63.000000,4.000000,200.000000,5.000000,5.000000

In [4]:
sleep_eff.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 452 entries, 0 to 451
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      452 non-null    int64
 1   Age                     452 non-null    int64
 2   Gender                  452 non-null    object
 3   Bedtime                 452 non-null    object
 4   Wakeup time             452 non-null    object
 5   Sleep duration          452 non-null    float64
 6   Sleep efficiency        452 non-null    float64
 7   REM sleep percentage    452 non-null    int64
 8   Deep sleep percentage   452 non-null    int64
 9   Light sleep percentage  452 non-null    int64
 10  Awakenings              432 non-null    float64
 11  Caffeine consumption    427 non-null    float64
 12  Alcohol consumption     438 non-null    float64
 13  Smoking status          452 non-null    object
 14  Exercise frequency      446 non-null    float64
dtypes: float64(6), int64(5), object(4)
memory usage: 53.1+ KB

In [5]:
sleep_eff.shape

(452, 15)

In [6]:
sleep_eff.isna().sum()

ID                         0
Age                        0
Gender                     0
Bedtime                    0
Wakeup time                0
Sleep duration             0
Sleep efficiency           0
REM sleep percentage       0
Deep sleep percentage      0
Light sleep percentage     0
Awakenings                20
Caffeine consumption      25
Alcohol consumption       14
Smoking status             0
Exercise frequency         6
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
cols=['ID','Age'	,'Gender'	,'Bedtime'	,'Wakeup time',	'Sleep duration',	'Sleep efficiency'	,'REM sleep percentage'	,'Deep sleep percentage'	,'Light sleep percentage',	'Awakenings','Caffeine consumption'	,'Alcohol consumption'	,'Smoking status','Exercise frequency']
for f in cols:
    sleep_eff[f]=le.fit_transform(sleep_eff[f])

In [8]:
sleep_eff.head()

,ID,Age,Gender,Bedtime,Wakeup time,Sleep duration,Sleep efficiency,REM sleep percentage,Deep sleep percentage,Light sleep percentage,Awakenings,Caffeine consumption,Alcohol consumption,Smoking status,Exercise frequency
0,0,56,0,65,65,2,38,1,26,3,0,0,0,1,3
1,1,60,1,394,402,3,16,2,7,23,3,0,3,1,3
2,2,31,0,151,151,5,39,3,26,1,1,0,0,0,3
3,3,31,0,349,358,2,1,6,5,22,3,2,5,1,1
4,4,48,1,76,75,5,26,10,16,9,3,0,3,0,3

In [9]:
sleep_eff['Smoking status'].value_counts()

Smoking status
0    298
1    154
Name: count, dtype: int64

In [10]:
X=sleep_eff.drop(columns='Smoking status',axis=1)
Y=sleep_eff['Smoking status']

In [11]:
print(X)

      ID  Age  Gender  Bedtime  Wakeup time  Sleep duration  Sleep efficiency  \
0      0   56       0       65           65               2                38
1      1   60       1      394          402               3                16
2      2   31       0      151          151               5                39
3      3   31       0      349          358               2                 1
4      4   48       1       76           75               5                26
..   ...  ...     ...      ...          ...             ...               ...
447  447   18       0      365          374               4                41
448  448   43       1       94           95               2                24
449  449   31       0      278          281               6                 5
450  450   36       1      226          229               3                26
451  451    9       1       78           77               4                13

     REM sleep percentage  Deep sleep percentage  Light sleep percentage  \
0                       1                     26                       3
1                       2                      7                      23
2                       3                     26                       1
3                       6                      5                      22
4                      10                     16                       9
..                    ...                    ...                     ...
447                     5                     18                      12
448                    11                     18                       6
449                     3                      9                      19
450                     1                     27                       1
451                     5                      3                      25

     Awakenings  Caffeine consumption  Alcohol consumption  Exercise frequency
0             0                     0                    0                   3
1             3                     0                    3                   3
2             1                     0                    0                   3
3             3                     2                    5                   1
4             3                     0                    3                   3
..          ...                   ...                  ...                 ...
447           0                     0                    0                   5
448           4                     1                    0                   3
449           1                     6                    3                   0
450           3                     0                    0                   3
451           1                     2                    0                   1

[452 rows x 14 columns]

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [13]:
print(X.shape,X_train.shape,X_test.shape)

(452, 14) (361, 14) (91, 14)

In [14]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

model.fit(X_train,Y_train)

C:\Users\Pulla\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [15]:
from sklearn.metrics import accuracy_score
pred=model.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score

In [16]:
confusion_matrix(Y_test,pred)

array([[52,  8],
       [20, 11]], dtype=int64)

In [18]:
accuracy_score(Y_test,pred)

0.6923076923076923

In [22]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(X_train,Y_train)
pred=model.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,pred))
print(accuracy_score(Y_test,pred))

[[58  2]
 [13 18]]
0.8351648351648352

In [23]:
input_data=(31,1,151,151,5,39,3,26,1,1	,0	,0	,0	,3)
input_data_as_numpy_array=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction=model.predict(input_data_reshaped)
print(prediction)
if prediction[0]==0:
    print('the person have sleep efficiency')
else:
  print('the person have not sufficient sleep')

[1]
the person have not sufficient sleep

C:\Users\Pulla\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [24]:
from sklearn.svm import SVC
model=SVC(kernel='linear')
model.fit(X_train,Y_train)
pred=model.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,pred))
print(accuracy_score(Y_test,pred))

[[50 10]
 [21 10]]
0.6593406593406593

In [25]:
import warnings

with warnings.catch_warnings():
    warnings.filterwarnings("ignore", message="X does not have valid feature names, but SVC was fitted with feature names")
input_data=(31,1,151,151,5,39,3,26,1,1	,0	,0	,0	,3)
input_data_as_numpy_array=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction=model.predict(input_data_reshaped)
print(prediction)
if prediction[0]==0:
    print('the person have sleep efficiency')
else:
  print('the person have not sufficient sleep')

[1]
the person have not sufficient sleep

C:\Users\Pulla\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [26]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=3)
model.fit(X_train,Y_train)
pred=model.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,pred))
print(accuracy_score(Y_test,pred))

[[49 11]
 [22  9]]
0.6373626373626373

In [27]:
input_data=(31,1,151,151,5,39,3,26,1,1	,0	,0	,0	,3)
input_data_as_numpy_array=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction=model.predict(input_data_reshaped)
print(prediction)
if prediction[0]==0:
    print('the person have sleep efficiency')
else:
  print('the person have not sufficient sleep')

[1]
the person have not sufficient sleep

C:\Users\Pulla\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(

In [28]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_train,Y_train)
pred=model.predict(X_test)
from sklearn.metrics import confusion_matrix,accuracy_score
print(confusion_matrix(Y_test,pred))
print(accuracy_score(Y_test,pred))

[[44 16]
 [12 19]]
0.6923076923076923

In [29]:
input_data=(31,1,151,151,5,39,3,26,1,1	,0	,0	,0	,3)
input_data_as_numpy_array=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction=model.predict(input_data_reshaped)
print(prediction)
if prediction[0]==0:
    print('the person have sleep efficiency')
else:
  print('the person have not sufficient sleep')

[0]
the person have sleep efficiency

C:\Users\Pulla\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(